spring:
  application:
    name: rabbitmq-playground
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      rabbit: # tu nasz broker kolejki - rabbit/Kafka itd
        bindings:
          input1: # tu nazwa channel'a (tutaj: MyConsumer.java -> INPUT1)
            consumer:
              autoBindDlq: true
      bindings:
        # producers
        output1: # namiar z MessageSource.java - nazwa w kodzie na Source'a
          destination: message-channel1 # nazwa exchange na RabbitMQ
          group: testowa-numero-1 # nazwa queue na RabbitMQ
        output2:
          destination: message-channel2
          group: testowa-numero-2
        # consumers
        input1: # namiar z MyConsumer.java - nazwa w kodzie na Sink'a
          destination: message-channel1 # nazwa exchange na RabbitMQ
          group: testowa-numero-1 # nazwa queue na RabbitMQ
        input2:
          destination: message-channel2
          group: testowa-numero-2
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      showDetails: ALWAYS

---

spring:
  profiles: test-docker-compose
  rabbitmq:
    host: rabbitmq
  cloud:
    inetutils:
      preferredNetworks:
        - 10.0.10

server:
  port: 8010

management:
  server:
    port: 8011
  info:
    git:
      mode: full

eureka:
  instance:
#    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    leaseRenewalIntervalInSeconds: 10
    healthCheckUrlPath: /actuator/health
    metadataMap:
      startup: ${random.int}
    preferIpAddress: true
  client:
    registryFetchIntervalSeconds: 10
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

---

spring:
  profiles: postgres
#   jpa:
#     hibernate:
#       ddl-auto: update
#     database-platform: org.hibernate.dialect.PostgreSQLDialect

db:
  driver-class-name: org.postgresql.Driver
  username: postgres
  password: postgres
  url: jdbc:postgresql://localhost:5432/postgres

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE

---

spring:
  profiles: postgres-local
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
